name: app_ui_kit
description: "A Flutter design system package with configurable theming, and UI components. Built to give consuming apps full control over colors and typography while keeping UI consistency.."
version: 0.1.0
homepage: https://uikit.vmgarcia.online
repository: https://github.com/vmgarciahurtado/app_ui_kit

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:


